### ISSUE TITLE
Formatter breaks queries including various postgres operators

### ISSUE THREAD

**Issue by pnezis** [akoutmos/sql_fmt#4]
This is a [bug of the rust crate](https://github.com/shssoichiro/sqlformat-rs/issues/52).

I would suggest to add a **WARNING** in the docs till this is fixed since it will break queries using such operators.

**Comment by akoutmos** [comment]
I think I have a temporary fix for this using regex replaces. Not an ideal long term solution but fixes this in the short term until the Rust library is fixed. Should be releasing that later today!

**Comment by akoutmos** [comment]
Going to be playing around with this for a bit but from some initial tests it seems to fix any issues introduced by the Rust library https://github.com/akoutmos/sql_fmt/commit/23ce12ec2c137f7d53e6727cc251d3e758d0f447

**Comment by pnezis** [comment]
I don't think it's that simple, this would introduce other issues, for example the following input:

```
SELECT 2 * -3
```

would be converted to `SELECT 2 *-3`. This may be a valid SQL but for other operators it will lead to invalid queries. The only guaranteed way to solve this is at the tokenisation level.

**Comment by akoutmos** [comment]
Good points. Perhaps another route needs to be explored if these issues cannot be sorted out in the sqlformat-rs package.

There is the https://github.com/apache/datafusion-sqlparser-rs project which offers a lexer and parser for various SQL dialects. But there is no formatter provided so I (or we if you are interested lol) would have to build one after the library generates the AST of the provided SQL statements. The library provides a `Visitor` trait for the various https://docs.rs/sqlparser/latest/sqlparser/ast/trait.Visitor.html AST nodes...so a formatted should be possible. The added benefit of using an actual lexer+parser is that it will generate error messages for invalid SQL whereas right no sqlformat-rs is happy to process whatever you give it.

**Comment by pnezis** [comment]
Implementing a formatter given an AST is doable but it will need a lot of work. On the other hand fixing tokenisation of operators on the `sqlformat-rs` package is much easier. 

My only concern currently is if `sqlformat-rs` is production ready and if any other such bug exists. In our case the test suite broke, but a formatter that modifies the sql queries may lead to subtle bugs that they will be a nightmare to detect.

**Comment by dkuku** [comment]
It gave it a [try](https://github.com/shssoichiro/sqlformat-rs/pull/57).

**Comment by akoutmos** [comment]
Awesome work @dkuku!! Soon as a new release of [sqlformat-rs](https://github.com/shssoichiro/sqlformat-rs) is cut I'll update sql_fmt. Thanks for tackling this!

**Comment by akoutmos** [comment]
Just released 0.3.0 with the latest version of sqlformat-rs where this issue is now fixed!
